pinaxcon/registrasion/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    "pinaxcon.registrasion.views",
    url(r"^demopay/([0-9]+)/([A-Z0-9]+)$", views.demopay, name="demopay"),
)

pinaxcon/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.views.generic import TemplateView

from django.contrib import admin

import symposion.views


urlpatterns = [
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),

    url(r"^teams/", include("symposion.teams.urls")),

    # Required by registrasion
    url(r'^tickets/payments/', include('registripe.urls')),
    url(r'^tickets/', include('registrasion.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),

    url(r'^dashboard/', RedirectView.as_view(url='/')),
    url(r'^$', symposion.views.dashboard, name="dashboard"),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, url(r'^__debug__/', include(debug_toolbar.urls)))


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinaxcon/proposals/models.py
from django.db import models

from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):

    TARGET_USER = 1
    TARGET_BUSINESS = 2
    TARGET_COMMUNITY = 3
    TARGET_DEVELOPER = 4

    TARGET_AUIDENCES = [
        (TARGET_USER, "User"),
        (TARGET_BUSINESS, "Business"),
        (TARGET_COMMUNITY, "Community"),
        (TARGET_DEVELOPER, "Developer"),
    ]

    target_audience = models.IntegerField(choices=TARGET_AUIDENCES)

    recording_release = models.BooleanField(
        default=True,
        help_text="I allow Linux Australia to release any recordings of "
        "presentations covered by this proposal, under the <a "
        "href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> "
        "Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"
    )

    materials_release = models.BooleanField(
        default=True,
        help_text="I allow Linux Australia to release any other material "
        "(such as slides) from presentations covered by this proposal, under "
        "the <a "
        "href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> "
        "Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"
    )

    class Meta:
        abstract = True


class TalkProposal(Proposal):

    class Meta:
        verbose_name = "talk proposal"


class TutorialProposal(Proposal):

    class Meta:
        verbose_name = "tutorial proposal"


class MiniconfProposal(Proposal):

    target_audience = models.IntegerField(choices=Proposal.TARGET_AUIDENCES,
                                          default=Proposal.TARGET_DEVELOPER)

    class Meta:
        verbose_name = "miniconf proposal"

pinaxcon/registrasion/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django_countries.fields import CountryField
from registrasion import models as rego


@python_2_unicode_compatible
class PastEvent(models.Model):
    ''' This is populated in 0001_initial.py '''

    def __str__(self):
        return self.name

    year = models.IntegerField(unique=True,)
    name = models.CharField(max_length=255, unique=True,)


class AttendeeProfile(rego.AttendeeProfileBase):

    @classmethod
    def name_field(cls):
        ''' This is used to pre-fill the attendee's name from the
        speaker profile. If it's None, that functionality is disabled. '''
        return "name"

    def invoice_recipient(self):

        lines = [
            self.name_per_invoice,
        ]

        if self.company:
            lines.append("C/- " + self.company)

        if self.address_line_1:
            lines.append(self.address_line_1)

        if self.address_line_2:
            lines.append(self.address_line_2)

        if self.address_suburb or self.address_postcode:
            lines.append("%s %s" % (
                self.address_suburb or "",
                self.address_postcode or "",
            ))

        if self.state:
            lines.append(self.state)

        if self.country:
            lines.append(self.country.name)

        return "\n".join(lines)

    def clean(self):
        errors = []
        if self.country == "AU" and not self.state:
            errors.append(
                ("state", "Australians must list their state"),
            )

        if self.address_line_2 and not self.address_line_1:
            errors.append((
                "address_line_1",
                "Please fill in line 1 before filling line 2",
            ))

        if errors:
            raise ValidationError(dict(errors))

    def save(self):
        if not self.name_per_invoice:
            self.name_per_invoice = self.name
        super(AttendeeProfile, self).save()

    # Things that appear on badge
    name = models.CharField(
        verbose_name="Your name (for your conference nametag)",
        max_length=64,
        help_text="Your name, as you'd like it to appear on your badge. ",
    )
    company = models.CharField(
        max_length=64,
        help_text="The name of your company, as you'd like it on your badge",
        blank=True,
    )

    free_text_1 = models.CharField(
        max_length=64,
        verbose_name="Free text line 1",
        help_text="A line of free text that will appear on your badge. Use "
                  "this for your Twitter handle, IRC nick, your preferred "
                  "pronouns or anything else you'd like people to see on "
                  "your badge.",
        blank=True,
    )
    free_text_2 = models.CharField(
        max_length=64,
        verbose_name="Free text line 2",
        blank=True,
    )

    # Other important Information
    name_per_invoice = models.CharField(
        verbose_name="Your legal name (for invoicing purposes)",
        max_length=256,
        help_text="If your legal name is different to the name on your badge, "
                  "fill this in, and we'll put it on your invoice. Otherwise, "
                  "leave it blank.",
        blank=True,
        )

    address_line_1 = models.CharField(
        verbose_name="Address line 1",
        help_text="This address, if provided, will appear on your invoices.",
        max_length=1024,
        blank=True,
    )
    address_line_2 = models.CharField(
        verbose_name="Address line 2",
        max_length=1024,
        blank=True,
    )
    address_suburb = models.CharField(
        verbose_name="City/Town/Suburb",
        max_length=1024,
        blank=True,
    )
    address_postcode = models.CharField(
        verbose_name="Postal/Zip code",
        max_length=1024,
        blank=True,
    )
    country = CountryField(
        default="AU",
    )
    state = models.CharField(
        max_length=256,
        verbose_name="State/Territory/Province",
        blank=True,
    )

    of_legal_age = models.BooleanField(
        verbose_name="Are you over 18?",
        help_text="Being under 18 will not stop you from attending the "
                  "conference. We need to know whether you are over 18 to "
                  "allow us to cater for you at venues that serve alcohol.",
    )
    dietary_restrictions = models.CharField(
        verbose_name="Food allergies, intolerances, or dietary restrictions",
        max_length=256,
        blank=True,
    )
    accessibility_requirements = models.CharField(
        verbose_name="Accessibility-related requirements",
        max_length=256,
        blank=True,
    )
    gender = models.CharField(
        help_text="Gender data will only be used for demographic purposes.",
        max_length=64,
        blank=True,
    )

    linux_australia = models.BooleanField(
        verbose_name="Linux Australia membership",
        help_text="Select this field to register for free "
                  "<a href='http://www.linux.org.au/'>Linux Australia</a> "
                  "membership.",
        blank=True,
    )

    lca_announce = models.BooleanField(
        verbose_name="Subscribe to lca-announce list",
        help_text="Select to be subscribed to the low-traffic lca-announce "
                  "mailing list",
        blank=True,
    )

    lca_chat = models.BooleanField(
        verbose_name="Subscribe to the lca2017-chat list",
        help_text="lca2017-chat is a high-traffic mailing list used by "
                  "attendees during the week of the conference for general "
                  "discussion.",
        blank=True,
    )

    past_lca = models.ManyToManyField(
        PastEvent,
        verbose_name="Which past linux.conf.au events have you attended?",
        blank=True,
    )

pinaxcon/proposals/forms.py
from django import forms

from pinaxcon.proposals.models import TalkProposal, TutorialProposal, MiniconfProposal


class ProposalForm(forms.ModelForm):

    required_css_class = 'label-required'

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class MiniconfProposalForm(ProposalForm):

    class Meta:
        model = MiniconfProposal
        fields = [
            "title",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "recording_release",
            "materials_release",
        ]

pinaxcon/registrasion/forms.py
from pinaxcon.registrasion import models

from django import forms


class YesNoField(forms.TypedChoiceField):

    def __init__(self, *args, **kwargs):
        kwargs['required'] = True
        super(YesNoField, self).__init__(
            *args,
            coerce=lambda x: x is True,
            choices=((None, '--------'), (False, 'No'), (True, 'Yes')),
            **kwargs
        )


class ProfileForm(forms.ModelForm):
    ''' A form for requesting badge and profile information. '''

    required_css_class = 'label-required'

    class Meta:
        model = models.AttendeeProfile
        exclude = ['attendee']
        widgets = {
            'past_lca': forms.widgets.CheckboxSelectMultiple
        }
        field_classes = {
            "of_legal_age": YesNoField,
        }

pinaxcon/registrasion/views.py
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from registrasion import models as rego
from registrasion.controllers.invoice import InvoiceController

from pinaxcon.registrasion import models


def demopay(request, invoice_id, access_code):
    ''' Marks the invoice with the given invoice id as paid.
    '''
    invoice_id = int(invoice_id)
    inv = get_object_or_404(rego.Invoice.objects, pk=invoice_id)

    invoice = InvoiceController(inv)

    if not invoice.can_view(user=request.user, access_code=access_code):
        raise Http404()

    to_invoice = redirect("invoice", invoice.invoice.id, access_code)

    try:
        invoice.validate_allowed_to_pay()  # Verify that we're allowed to do this.
    except ValidationError as ve:
        messages.error(request, ve.message)
        return to_invoice

    # Create the payment object
    models.DemoPayment.objects.create(
        invoice=invoice.invoice,
        reference="Demo payment by user: " + request.user.username,
        amount=invoice.invoice.value,
    )

    invoice.update_status()

    messages.success(request, "This invoice was successfully paid.")

    return to_invoice

pinaxcon/templates/symposion/schedule/_edit_grid.html
<table class="calendar table table-bordered">
    <thead>
        <tr>
            <th class="time">&nbsp;</th>
            {% for room in timetable.rooms %}
                <th>{{ room.name }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for row in timetable %}
            <tr>
                <td class="time">{{ row.time|date:"h:iA" }}</td>
                {% for slot in row.slots %}
                    <td class="slot slot-{{ slot.kind.label }}" colspan="{{ slot.colspan }}" rowspan="{{ slot.rowspan }}">
                        {% if slot.kind.label == "talk" or slot.kind.label == "tutorial" %}
                            {% if not slot.content %}
                                <a class="btn btn-xs edit-slot" data-action="{% url "schedule_slot_edit" schedule.section.slug slot.pk %}" href="#">+</a>
                            {% else %}
                                <span class="title"><a class="edit-slot" data-action="{% url "schedule_slot_edit" schedule.section.slug slot.pk %}" href="#">{{ slot.content.title }}</a></span>
                                <span class="speaker">{{ slot.content.speaker }}</span>
                            {% endif %}
                        {% else %}
                            {% if slot.content_override.raw %}
                                {{ slot.content_override.rendered|safe }}
                            {% else %}
                                {{ slot.kind.label }}
                            {% endif %}
                            &mdash; <a class="edit-slot" data-action="{% url "schedule_slot_edit" schedule.section.slug slot.pk %}" href="#">edit</a>
                        {% endif %}
                    </td>
                {% endfor %}
                {% if forloop.last %}
                    <td colspan="{{ timetable.rooms|length }}"></td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>

pinaxcon/templates/symposion/schedule/_grid.html
{% load pyconau2017_tags %}
<table class="calendar table table-bordered">
  <thead>
    <tr>
      <th class="time">&nbsp;</th>
        {% for room in timetable.rooms %}
          <th>{{ room.name }}</th>
          {% endfor %}
    </tr>
    <tr>
      <th class="time">&nbsp;</th>
        {% for room in timetable.rooms %}
          {% with room|trackname:timetable.day as track_name %}
          <th class="track-name">{% if track_name %}<p>{{ track_name }}{% endif %}</th>
	  {% endwith %}
        {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for row in timetable %}
      <tr>
        <td class="time"><h4>{{ row.time|date:"h:iA" }}</h4></td>
        {% for slot in row.slots %}
          <td class="slot slot-{{ slot.kind.label }}" colspan="{{ slot.colspan }}" rowspan="{{ slot.rowspan }}">
            {% if slot.kind.label == "talk" or slot.kind.label == "tutorial" %}
              {% if not slot.content %}
              {% else %}
                <span class="title">
                  <a href="{% url "schedule_presentation_detail" slot.content.pk %}">{{ slot.content.title }}</a>
                </span>
                <span class="speaker">
                  {{ slot.content.speakers|join:", " }}
                </span>
                <span class="room">
                  {{ slot.rooms|join:", "}}
                </span>
              {% endif %}
            {% elif slot.kind.label == "shortbreak" %}
            {% else %}
              {% if slot.content_override %}
                {{ slot.content_override_html|safe }}
              {% else %}
                {{ slot.kind.label }}
              {% endif %}
            {% endif %}
          </td>
        {% endfor %}
        {% if forloop.last %}
          <td colspan="{{ timetable.rooms|length }}"></td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

pinaxcon/templates/symposion/schedule/_slot_edit.html
{% load i18n bootstrap %}
<form class="form-horizontal" id="slotEditForm" class="modal-form" method="POST" action="{% url "schedule_slot_edit" slug slot.pk %}">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3>{% trans "Edit Slot" %}</h3>
    </div>
    <div class="modal-body" style="height:350px">
        {% csrf_token %}
        {{ form|bootstrap }}
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

pinaxcon/templates/symposion/schedule/base.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block extra_style %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/site-0a247b924d.css' %}">
{% endblock %}

{% block body_base %}
  <div style="height: 100px;" />
  <main role="main">
    {% include "_messages.html" %}
    {% block body %}
      {% block content %}
      {% endblock %}
    {% endblock %}
  </main>
{% endblock %}

{% block scripts %}
  <script src="{{ STATIC_URL }}/js/app.js" type="text/javascript"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
  <script src="{{ STATIC_URL }}/js/bootstrap.min.js" type="text/javascript"></script>
  {% block extra_script %}{% endblock %}
{% endblock %}

{% block extra_body_base %}
  {% block analytics %}
    {% include "analytics.html" %}
  {% endblock %}
  {% block extra_body %}{% endblock %}
{% endblock %}

pinaxcon/templates/symposion/schedule/presentation_detail.html
{% extends "symposion/schedule/public_base.html" %}

{% load pyconau2017_tags %}
{% load sitetree %}
{% load staticfiles %}
{% load thumbnail %}

{% block head_title %}Presentation: {{ presentation.title }}{% endblock %}

{% block breadcrumbs %}{% sitetree_breadcrumbs from "main" %}{% endblock %}

{% block header_inset_image %}{% with audience=presentation.proposal.get_target_audience_display %}{% if audience == "Business" %}{% illustration "falls.svg" %}{% elif audience == "Community" %}{% illustration "bridge.svg" %}{% elif audience == "Developer"%}{% illustration "hobart.svg" %}{% elif audience == "User" %}{% illustration "antarctica.svg" %}{% else %}{% illustration "casino.svg" %}{% endif %}{% endwith %}{% endblock %}

{% block header_background_image %}{% presentation_bg_number presentation 4 as bg_number %}{% if bg_number == 0 %}{% static "pyconau2017/images/mt_anne_bg_optimised.jpg" %}{% elif bg_number == 1 %}{% static "pyconau2017/images/the_neck_bg_optimised.jpg" %}{% elif bg_number == 2 %}{% static "pyconau2017/images/snug_falls_bg_optimised.jpg" %}{% elif bg_number == 3 %}{% static "pyconau2017/images/sleepy_bay_bg_optimised.jpg" %}{% endif %}{% endblock %}

{% block header_title %}{{ presentation.title }}{% endblock %}

{% block header_paragraph %}
  <p>
    Presented by
    {% for speaker in presentation.speakers %}
      <a href="{% url "speaker_profile" speaker.pk %}">{{ speaker }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
  <br />
  {% if presentation.slot %}
    {{ presentation.slot.day.date|date:"l" }}
    {{ presentation.slot.start}}&ndash;{{ presentation.slot.end }}
    <br />
  {% endif %}
  {% if presentation.proposal.get_target_audience_display %}
    <strong>Target audience:</strong>
    {{ presentation.proposal.get_target_audience_display }}
  {% endif %}
{% endblock %}

{% block content %}

  {% if presentation.unpublish %}
    <p><strong>Presentation not published.</strong></p>
  {% endif %}

  <h2>Abstract</h2>

  <div class="abstract">{{ presentation.abstract_html|safe }}</div>

  <h2>Presented by</h2>
  {% for speaker in presentation.speakers %}
    {% speaker_photo speaker 512 as speaker_photo_url %}
    {% include "_right_floating_image.html" with image_url=speaker_photo_url %}

    <h3><a href="{% url "speaker_profile" speaker.pk %}">{{ speaker }}</a></h3>

    {% if speaker.homepage or speaker.twitter_username %}
      <p><div class="btn-group">
        {% if speaker.homepage %}
          <a href="{{ speaker.homepage}}" class="btn-svg" title="Homepage">
            {% include "cms_pages/home_page_blocks/btn_generic_link.html" %}
          </a>
        {% endif %}
        {% if speaker.twitter_username %}
          <a href="https://twitter.com/{{ speaker.twitter_username }}" class="btn-svg" title="{{ speaker}} on twitter">
            {% include "cms_pages/home_page_blocks/btn_twitter.html" %}
          </a>
        {% endif %}
      </div></p>
    {% endif %}



    {{ speaker.biography_html|safe}}

  {% endfor %}

{% endblock %}

pinaxcon/templates/symposion/schedule/public_base.html
{% extends "content_page.html" %}

{% load staticfiles %}

{% comment %}
{% block header_background_image %}{% static "pyconau2017/images/hobart_bg_optimised.jpg" %}{% endblock %}
{% endcomment %}

pinaxcon/templates/symposion/schedule/schedule_conference.html
{% extends "symposion/schedule/public_base.html" %}

{% load i18n %}
{% load cache %}
{% load pyconau2017_tags %}

{% block head_title %}Conference Schedule{% endblock %}
{% block header_title %}Conference Schedule{% endblock %}

{% block body_class %}full{% endblock %}

{% block right %}
{% endblock %}

{% block content_base %}

  <div class="page-head">
    {% block breadcrumbs %}{% endblock %}
  </div>

  <div class="panel panel__compact">
    <div class="panel--content">

      <div class="panel--tab-controls">
        <div class="panel--tabs">
          {% for section in sections %}
            {% for timetable in section.days %}
              <a
                data-tab-control="{{ timetable.day.date|date:"l"}}"
                id="schedule_day_{{ timetable.day.date|date:"l"|lower}}"
                class="panel--tab-switch is-active">
                  {{ timetable.day.date|date:"l"}}
              </a>
            {% endfor %}
          {% endfor %}
        </div>
      </div>

      {% for section in sections %}
         {% cache 600 "schedule-table" section.schedule.section %}
            {% for timetable in section.days %}
              <div data-tab-content="{{ timetable.day.date|date:"l"}}" class="panel--tab-content is-active">
                <h3>{{ section.schedule.section.name }} — {{ timetable.day.date|date:"l" }}, {{ timetable.day.date }}</h3>
                {% include "symposion/schedule/_grid.html" %}
              </div>
            {% endfor %}
         {% endcache %}
      {% endfor %}

    </div>
  </div>
{% endblock %}

{% block scripts_extra %}
  <script type="text/javascript">

    fragment = window.location.hash.toLowerCase().substring(1);

    if (!fragment) {
      OFFSET = -11 * (60 * 60 * 1000); // Hobart is 11 hours ahead of UTC in Jan.
      JAN = 0; // because January is 0, not 1

      fragments = [
        {"day": "monday", "time": Date.UTC(2017, JAN, 16)},
        {"day": "tuesday", "time": Date.UTC(2017, JAN, 17)},
        {"day": "wednesday", "time": Date.UTC(2017, JAN, 18)},
        {"day": "thursday", "time": Date.UTC(2017, JAN, 19)},
        {"day": "friday", "time": Date.UTC(2017, JAN, 20)},
        {"day": "saturday", "time": Date.UTC(2017, JAN, 21)},
      ];

      now = new Date().getTime();

      for (i = 0; i < 5; i++) {
        f = fragments[i];
        g = fragments[i+1];
        if ((f.time + OFFSET) <= now && now < (g.time + OFFSET)) {
          fragment = f.day;
        }
      }
    }

    document.addEventListener("DOMContentLoaded", function(event) {

      if (!fragment) {
        return;
      }

      fragmentSwitch = "schedule_day_" + fragment;

      switches = document.getElementsByClassName("panel--tab-switch");
      tabs = document.getElementsByClassName("panel--tab-content");

      for (i = 0; i < switches.length; i++) {

        if (switches[i].id == fragmentSwitch) {
          switches[i].classList.add("is-active");
          tabs[i].classList.add("is-active");
        } else {
          switches[i].classList.remove("is-active");
          tabs[i].classList.remove("is-active");
        }
      }

    });

    window.addEventListener("load", function(event) {

      $(".panel--tab-switch").click(function(event) {
        // This updates the window location fragment so that
        // the URL bar is updated, and so that when you go
        // back, it loads the right page.

        // len("schedule_day_") == 13
        day = event.target.id.substring(13);

        if(history.pushState) {
            history.pushState(null, null, "#" + day);
        }
      });
    });

  </script>
  {{ block.super }}
{% endblock %}

pinaxcon/templates/symposion/schedule/schedule_detail.html
{% extends "symposion/schedule/public_base.html" %}

{% load i18n %}
{% load cache %}
{% load pyconau2017_tags %}
{% load sitetree %}

{% block head_title %}{{ schedule.section }} Schedule{% endblock %}
{% block header_title %}{{ schedule.section }} Schedule{% endblock%}
{% block header_paragraph %}{{ schedule.header_paragraph.text }}{% endblock%}
{% block header_inset_image %}{% illustration "devil.svg" %}{% endblock %}

{% block body_class %}full{% endblock %}

{% block content %}
  <div class="page-head">
    {% block breadcrumbs %}{% sitetree_breadcrumbs from "main" %}{% endblock %}
  </div>

  {% cache 600 "schedule-table" schedule.section %}
    {% for timetable in days %}
      <h3>{{ timetable.day.date|date:"l" }}, {{ timetable.day.date }}</h3>
      <br />
      {% include "symposion/schedule/_grid.html" %}
      <br />
    {% endfor %}
  {% endcache %}
{% endblock %}

pinaxcon/templates/symposion/schedule/schedule_edit.html
{% extends "symposion/schedule/base.html" %}

{% load i18n %}

{% block head_title %}Conference Schedule Edit{% endblock %}

{% block body_class %}full{% endblock %}

{% block right %}
{% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}
<div class="l-content-page">
<div class="l-content-page--richtext">
<div class="rich-text">

    <h1>Schedule Edit</h1>

    {% for timetable in days %}
        <h2>{{ timetable.day.date }}</h2>
        {% include "symposion/schedule/_edit_grid.html" %}
    {% endfor %}
    <form class="form-horizontal" id="schedule-builder" action="." method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Submit" />
        <input type="submit" id="delete" name="delete" value="Delete Schedule" />
    </form>
    <div class="modal fade in" style="background-color:#fff;" id="slotEditModal"></div>
</div></div></div>
{% endblock %}

{% block extra_script %}
    <script type="text/javascript">
        $(function() {
            $("a.edit-slot").click(function(e) {
                $("#slotEditModal").load($(this).data("action"), function() {
                    $("#slotEditModal").modal("show");
                });
                e.preventDefault();
            });
        });
        $(function() {
           //submit event handler
            $("form#schedule-builder :submit").click(function(e) {
                var name = this.name;
                if(name == 'delete') {
                    if (!confirm("Are you sure you want to delete the schedule?"))
                        {
                            e.preventDefault();
                            return;
                        }
                }
            });
        });

    </script>
{% endblock %}

pinaxcon/templates/symposion/schedule/schedule_list.html
{% extends "symposion/schedule/public_base.html" %}

{% load i18n %}
{% load cache %}
{% load pyconau2017_tags %}
{% load sitetree %}

{% block head_title %}Presentation Listing{% endblock %}

{% block header_title %}{{ schedule.section.name }} List{% endblock %}
{% block header_paragraph %}{{ schedule.header_paragraph.text }}{% endblock%}
{% block header_inset_image %}{% illustration "lavender.svg" %}{% endblock %}

{% block breadcrumbs %}{% sitetree_breadcrumbs from "main" %}{% endblock %}

{% block content %}
<div class="jumbotron">
  {% cache 600 "schedule-list" schedule.section.name %}
    <ul>
      {% for presentation in presentations %}
        <li>
          <a href="{% url "schedule_presentation_detail" presentation.pk %}">{{ presentation.title }}</a> {{ presentation.proposal.kind }} <em>by</em>
          {{ presentation.speakers|join:", " }}
          {% if presentation.slot %}
            ({{ presentation.slot.day.date|date:"l" }}
            {{ presentation.slot.start}}&ndash;{{ presentation.slot.end }}
            in
            {{ presentation.slot.rooms|join:", " }})
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% endcache %}
</div>
{% endblock %}